# Generated by Django 2.0 on 2021-01-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_question_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='qOption',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
