# Generated by Django 2.0 on 2021-01-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_question_yes_no_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='yes_no_question',
        ),
        migrations.AddField(
            model_name='question',
            name='si_no',
            field=models.BooleanField(default=False, help_text="Check the box to automatically add the 'Si' and 'No' options. Take into account that no more options will be admited. ", verbose_name='Yes/No question'),
        ),
    ]
