# Generated by Django 2.0 on 2021-01-04 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_voting_qoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='qOption',
        ),
    ]
