# Generated by Django 2.0 on 2021-01-14 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20210107_1809'),
        ('voting', '0004_auto_20210104_1944'),
    ]

    operations = [
    ]
