# Generated by Django 2.0 on 2021-01-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_merge_20210109_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='preferences',
            field=models.BooleanField(default=False, help_text='Check for creating a preference question', verbose_name='Preferences'),
        ),
        migrations.AddField(
            model_name='voting',
            name='qOption',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
