# Generated by Django 2.0 on 2021-01-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_voting_qoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='qOption',
            field=models.IntegerField(null=True),
        ),
    ]
