# Generated by Django 2.0 on 2021-01-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_auto_20210112_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoption',
            name='qOption',
        ),
        migrations.AddField(
            model_name='voting',
            name='qOption',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
