# Generated by Django 2.0 on 2021-01-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_auto_20210106_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='qOption',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
