# Generated by Django 2.0 on 2021-01-11 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_auto_20210104_1944'),
        ('voting', '0009_auto_20210106_1852'),
        ('voting', '0005_auto_20210107_1809'),
    ]

    operations = [
    ]
