# Generated by Django 2.0 on 2021-01-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_auto_20210112_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='qOption',
        ),
        migrations.AddField(
            model_name='questionoption',
            name='qOption',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
