# Generated by Django 2.0 on 2021-01-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0013_auto_20210112_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='qOption',
        ),
    ]
