# Generated by Django 2.0 on 2021-01-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0014_remove_question_qoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='qOption',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
