# Generated by Django 2.0 on 2021-01-14 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_merge_20210114_1000'),
        ('voting', '0014_remove_question_qoption'),
    ]

    operations = [
    ]
