# Generated by Django 2.0 on 2021-01-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0015_question_qoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='qOption',
        ),
        migrations.AddField(
            model_name='voting',
            name='qOption',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
