# Generated by Django 2.0 on 2021-01-14 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0016_auto_20210114_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='qOption',
        ),
    ]
