# Generated by Django 2.0 on 2021-01-15 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0017_remove_voting_qoption'),
        ('voting', '0015_merge_20210114_1639'),
    ]

    operations = [
    ]
